name: Build and Deploy Testing
on:
  push:
    branches:
      - testing
jobs:
  build-and-deploy-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Build 🔧
        run: |
          npm install
          npm run build-testing

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dist # The branch the action should deploy to.
          folder: releases # The folder the action should deploy.
          clean: false # build is already clean (keep prod/dev)
